const nodes=window.CHATBOT_NODES;const chat=document.getElementById('chat'),input=document.getElementById('questionInput'),typing=document.getElementById('typing'),crumbs=document.getElementById('breadcrumbs');let current='main',history=[],path=[];
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ ]/g,' ');const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const time=()=>new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});const scroll=()=>setTimeout(()=>chat.scrollTop=chat.scrollHeight,30);
function bubble(html,who='bot'){let d=document.createElement('div');d.className='bubble '+who;d.innerHTML=html+`<div class="time">${time()}</div>`;chat.appendChild(d);scroll();return d}function user(t){bubble(esc(t),'me')}
function renderCrumbs(){crumbs.textContent=path.length?'Inicio › '+path.map(x=>x.label).join(' › '):'Inicio'}
function showTyping(cb){typing.classList.remove('hidden');scroll();setTimeout(()=>{typing.classList.add('hidden');cb()},450)}
function attachments(node,box){if(!node.attachments)return;let a=document.createElement('div');a.className='actions';node.attachments.forEach(att=>{if(att.type==='image'){let link=document.createElement('a');link.href=att.link||att.url;link.target='_blank';link.rel='noopener noreferrer';let img=document.createElement('img');img.src=att.url;img.className='attachment-img';img.alt='Abrir recurso';link.appendChild(img);a.appendChild(link)}else if(att.type==='video'){let u=(att.url.match(/src="([^"]+)"/)||[])[1];let b=document.createElement('button');b.textContent='▶ Ver video';b.onclick=()=>openViewer(u);a.appendChild(b)}else if(att.type==='link'){let b=document.createElement('button');b.textContent=att.title||'Abrir recurso';b.onclick=()=>att.url.toLowerCase().includes('.pdf')?openViewer(att.url):window.open(att.url,'_blank','noopener');a.appendChild(b)}});box.appendChild(a)}
function feedback(box){let d=document.createElement('div');d.className='feedback';d.innerHTML='¿Te sirvió esta respuesta? <button>👍 Sí</button><button>👎 No</button>';let bs=d.querySelectorAll('button');bs[0].onclick=()=>{d.textContent='Gracias por tu opinión.';track('feedback_si')};bs[1].onclick=()=>{d.innerHTML='Lamentamos que no resolviera tu duda. <button id="advisor">Hablar con asesor</button>';d.querySelector('#advisor').onclick=()=>window.open('https://wa.me/529372547287?text='+encodeURIComponent('Hola, necesito apoyo del área de Recaudación. Mi consulta no fue resuelta por el Asistente Abordo.'),'_blank');track('feedback_no')};box.appendChild(d)}
function present(id,add=true,label=''){let n=nodes[id];if(!n)return bubble('No pude localizar esa información.');if(add&&current){history.push({id:current,path:[...path]});if(label)path.push({id,label})}current=id;renderCrumbs();showTyping(()=>{if(n.type==='question'){bubble('<strong>'+esc(n.prompt)+'</strong>');let opts=document.createElement('div');opts.className='options';n.options.forEach(o=>{let b=document.createElement('button');b.className='option-btn';b.textContent=o.label;b.onclick=()=>{user(o.label);if(/REGRESAR/i.test(o.label))back();else present(o.next,true,o.label)};opts.appendChild(b)});chat.appendChild(opts)}else{let box=bubble('<div>'+esc(n.text).replace(/\n/g,'<br>')+'</div><div class="notice">Información orientativa; valida importes y requisitos vigentes con el área correspondiente.</div>');attachments(n,box);feedback(box);let opts=document.createElement('div');opts.className='options';let b=document.createElement('button');b.className='option-btn';b.textContent='← Regresar';b.onclick=back;opts.appendChild(b);chat.appendChild(opts)}track('view_'+id);scroll()})}
function back(){if(!history.length)return home();let h=history.pop();current=h.id;path=h.path;renderCrumbs();present(current,false)}function home(){chat.innerHTML='';history=[];path=[];current='main';renderCrumbs();present('main',false)}
function score(q,n){let hay=norm([n.prompt,n.text,...(n.options||[]).map(o=>o.label)].join(' '));let words=norm(q).split(/\s+/).filter(w=>w.length>2);return words.reduce((s,w)=>s+(hay.includes(w)?1:0),0)}
function search(q){let nq=norm(q);if(!nq)return;if(/inicio|menu principal/.test(nq)){home();return}if(/regresar|volver|atras/.test(nq)){back();return}let direct=Object.entries(nodes).map(([id,n])=>({id,n,s:score(q,n)})).sort((a,b)=>b.s-a.s);if(!direct[0]||direct[0].s<1){bubble('No encontré una coincidencia clara. Prueba con palabras como “ISR”, “Fonacot”, “liquidación”, “sueldo” o “asesor”.');return}let r=direct[0];bubble(`Encontré información relacionada con <strong>${esc(q)}</strong>.`);present(r.id,true,r.n.prompt||r.n.text?.slice(0,35)||'Resultado')}
function send(){let q=input.value.trim();if(!q)return;user(q);input.value='';search(q)}document.getElementById('sendBtn').onclick=send;input.addEventListener('keydown',e=>{if(e.key==='Enter')send()});document.getElementById('homeBtn').onclick=home;document.getElementById('backBtn').onclick=back;
function openViewer(url){document.getElementById('viewer').classList.remove('hidden');document.getElementById('viewerFrame').src=url}document.getElementById('closeViewer').onclick=()=>{document.getElementById('viewer').classList.add('hidden');document.getElementById('viewerFrame').src=''};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(SR){rec=new SR();rec.lang='es-MX';rec.onresult=e=>{input.value=e.results[0][0].transcript;send()};rec.onerror=()=>bubble('No pude escuchar con claridad. También puedes escribir tu pregunta.')}else document.getElementById('micBtn').disabled=true;document.getElementById('micBtn').onclick=()=>rec&&rec.start();
function track(event){try{let x=JSON.parse(localStorage.getItem('chatboot_stats')||'{}');x[event]=(x[event]||0)+1;localStorage.setItem('chatboot_stats',JSON.stringify(x))}catch(e){}}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.getElementById('installBtn').classList.remove('hidden')});document.getElementById('installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');home();